# Site settings
# in the templates available like {{ site.myvariable }}.
title: หากเรานำความฝัน + การลงมือทำ = จะกลายเป็นความคิดที่มีตัวตน
email: singmax161@gmail.com
brand: แม็กคุง
headline: หากเรานำความฝัน + การลงมือทำ = จะกลายเป็นความคิดที่มีตัวตน
description: > # this means to ignore newlines until "baseurl:"
  อืมนะ...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://topexe.xyz" # the base hostname & protocol for your site
copyright: ถึงผมจะไม่มีแฟน แต่ผมมีหัวใจนะครับ

# Build settings
markdown: kramdown

# Account ids
snapwidget_top: 481943
snapwidget: 484045

# Contacts
email: singmax161@gmail.com
phone: +66-84-323-0445
phone2: 06-16-15-12-17
line: t.m_thongkum
line-url: http://line.me/ti/p/Lmhh7ptPN8
facebook: LoveThanachai
facebook-url: https://www.facebook.com/LoveThanachai
instagram: lovethanachai
instagram-url: https://www.instagram.com/lovethanachai/

# Tracking
googleAnalitycsID: UA-111102704-1
