# Site settings
# in the templates available like {{ site.myvariable }}.
title: Clean portfolio theme for Jekyll powered by Bootstrap 4.
email: singmax161@gmail.com
brand: แม็กคุง
headline: หากเรานำความฝัน + การลงมือทำ = จะกลายเป็นความคิดที่มีตัวตน
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 481935

# Contacts
email: singmax161@gmail.com
phone: +66-84-323-0445

# Tracking
googleAnalitycsID: UA-83933844-1

