# Site settings
# in the templates available like {{ site.myvariable }}.
title: หากเรานำความฝัน + การลงมือทำ = จะกลายเป็นความคิดที่มีตัวตน
email: singmax161@gmail.com
brand: แม็กคุง
headline: หากเรานำความฝัน + การลงมือทำ = จะกลายเป็นความคิดที่มีตัวตน
description: > # this means to ignore newlines until "baseurl:"
  อืมนะ...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: ถึงผมจะไม่มีแฟน แต่ผมมีหัวใจนะครับ

# Build settings
markdown: kramdown

# Account ids
snapwidget: 481943
snapwidget_top: 482098

# Contacts
email: singmax161@gmail.com
phone: +66-84-323-0445, 06-16-15-12-17
line: t.m_thongkum
line-web: http://line.me/ti/p/Lmhh7ptPN8
facebook: https://www.facebook.com/LoveThanachai
instagram: https://www.instagram.com/lovethanachai/

# Tracking
googleAnalitycsID: UA-111102704-1
